//! Build-time metadata for the optional bun runtime.
//!
//! When `AIONUI_EMBED_BUN=1` is set, this script downloads the bun binary
//! for the target platform, zstd-compresses it, and emits a `bun_meta.rs`
//! with the embedded blob, SHA256, and version. Without the env var it
//! emits a stub with `HAS_EMBEDDED_BUN = false`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=AIONUI_EMBED_BUN");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let meta_path = Path::new(&out_dir).join("bun_meta.rs");

    if env::var("AIONUI_EMBED_BUN").as_deref() == Ok("1") {
        match try_embed_bun(meta_path.as_path(), &out_dir) {
            Ok(()) => {}
            Err(error) => {
                println!("cargo:warning=AIONUI_EMBED_BUN=1 but embed failed ({error}), falling back to stub");
                write_meta_stub(meta_path.as_path(), &out_dir);
            }
        }
    } else {
        write_meta_stub(meta_path.as_path(), &out_dir);
    }
}

fn write_meta_stub(meta_path: &Path, out_dir: &str) {
    let stub_blob = Path::new(out_dir).join("bun.blob.zst");
    if !stub_blob.is_file() {
        fs::write(&stub_blob, []).expect("write stub blob");
    }
    let body = "// @generated by build.rs — do not edit\n\
                pub const BUN_BLOB: &[u8] = include_bytes!(\"bun.blob.zst\");\n\
                pub const BUN_SHA256: &str = \"\";\n\
                pub const BUN_VERSION: &str = \"\";\n\
                pub const HAS_EMBEDDED_BUN: bool = false;\n";
    fs::write(meta_path, body).expect("write stub bun_meta.rs");
}

fn try_embed_bun(meta_path: &Path, out_dir: &str) -> Result<(), String> {
    let target = env::var("TARGET").expect("TARGET");
    let bun_target = map_target_triple(&target)?;
    println!("cargo:warning=embedding bun for target {target} (bun target: {bun_target})");

    // Download latest release info from GitHub API.
    let (version, zip_url) = fetch_latest_bun_info(bun_target)?;
    println!("cargo:warning=downloading bun {version} from {zip_url}");

    // Download the zip.
    let zip_bytes = download_bytes(&zip_url).map_err(|e| format!("download failed: {e}"))?;

    // Extract bun binary from zip.
    let bun_binary = extract_bun_from_zip(&zip_bytes)?;
    println!("cargo:warning=extracted bun binary: {} bytes", bun_binary.len());

    // Compute SHA256 of uncompressed binary.
    let sha256 = {
        use sha2::{Digest, Sha256};
        hex::encode(Sha256::digest(&bun_binary))
    };

    // zstd compress.
    let compressed = zstd::bulk::compress(&bun_binary, 0).map_err(|e| format!("zstd compress failed: {e}"))?;

    // Write blob.
    let blob_path = Path::new(out_dir).join("bun.blob.zst");
    fs::write(&blob_path, &compressed).map_err(|e| format!("write blob: {e}"))?;

    // Write bun_meta.rs.
    let body = format!(
        "// @generated by build.rs — do not edit\n\
         pub const BUN_BLOB: &[u8] = include_bytes!(\"bun.blob.zst\");\n\
         pub const BUN_SHA256: &str = \"{sha256}\";\n\
         pub const BUN_VERSION: &str = \"{version}\";\n\
         pub const HAS_EMBEDDED_BUN: bool = true;\n"
    );
    fs::write(meta_path, body.as_bytes()).map_err(|e| format!("write bun_meta.rs: {e}"))?;

    Ok(())
}

/// Map Rust target triple to bun release naming convention.
fn map_target_triple(target: &str) -> Result<&'static str, String> {
    match target {
        "aarch64-apple-darwin" => Ok("darwin-aarch64"),
        "x86_64-apple-darwin" => Ok("darwin-x64"),
        "x86_64-pc-windows-msvc" => Ok("windows-x64"),
        "aarch64-pc-windows-msvc" => Ok("windows-aarch64"),
        "x86_64-unknown-linux-gnu" => Ok("linux-x64"),
        "aarch64-unknown-linux-gnu" => Ok("linux-aarch64"),
        _ => Err(format!("unsupported target triple for bun embedding: {target}")),
    }
}

/// Fetch the latest bun release tag and download URL from GitHub API.
fn fetch_latest_bun_info(bun_target: &str) -> Result<(String, String), String> {
    let client = build_http_client()?;
    let api_url = "https://api.github.com/repos/oven-sh/bun/releases/latest";
    let response = client
        .get(api_url)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .send()
        .map_err(|e| format!("GitHub API request failed: {e}"))?;

    if !response.status().is_success() {
        return Err(format!(
            "GitHub API returned HTTP {} for {api_url}",
            response.status().as_u16()
        ));
    }

    let body: serde_json::Value = response.json().map_err(|e| format!("parse GitHub API response: {e}"))?;

    let tag_name = body["tag_name"]
        .as_str()
        .ok_or_else(|| "missing tag_name in GitHub API response".to_string())?;

    // Extract version from tag (e.g., "bun-v1.2.5" → "1.2.5").
    let version = tag_name
        .strip_prefix("bun-v")
        .or_else(|| tag_name.strip_prefix("v"))
        .unwrap_or(tag_name);
    if version.is_empty() {
        return Err(format!("could not parse version from tag: {tag_name}"));
    }

    let download_url = format!("https://github.com/oven-sh/bun/releases/download/{tag_name}/bun-{bun_target}.zip");

    Ok((version.to_string(), download_url))
}

/// Download bytes from a URL using a blocking HTTP client.
fn download_bytes(url: &str) -> Result<Vec<u8>, String> {
    let client = build_http_client()?;
    let response = client
        .get(url)
        .send()
        .map_err(|e| format!("download request failed for {url}: {e}"))?;

    if !response.status().is_success() {
        return Err(format!(
            "download returned HTTP {} for {url}",
            response.status().as_u16()
        ));
    }

    response
        .bytes()
        .map(|b| b.to_vec())
        .map_err(|e| format!("read response bytes: {e}"))
}

/// Build a blocking HTTP client with reasonable timeouts.
fn build_http_client() -> Result<reqwest::blocking::Client, String> {
    reqwest::blocking::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(30))
        .timeout(std::time::Duration::from_secs(600))
        .user_agent(concat!("aioncore-bundler/", env!("CARGO_PKG_VERSION")))
        .build()
        .map_err(|e| format!("build HTTP client: {e}"))
}

/// Extract the `bun` (or `bun.exe`) binary from a bun release zip.
///
/// Bun zips contain a top-level directory like `bun-darwin-aarch64/`
/// with the binary inside, named `bun`.
fn extract_bun_from_zip(zip_bytes: &[u8]) -> Result<Vec<u8>, String> {
    let cursor = std::io::Cursor::new(zip_bytes);
    let mut archive = zip::ZipArchive::new(cursor).map_err(|e| format!("open zip: {e}"))?;

    let expected_name = if cfg!(target_family = "windows") {
        "bun.exe"
    } else {
        "bun"
    };

    for index in 0..archive.len() {
        let mut file = archive
            .by_index(index)
            .map_err(|e| format!("read zip entry {index}: {e}"))?;

        let file_name = file
            .name()
            .rsplit('/')
            .next()
            .or_else(|| file.name().rsplit('\\').next())
            .unwrap_or(file.name());

        if file_name == expected_name {
            let mut buf = Vec::with_capacity(file.size() as usize);
            std::io::copy(&mut file, &mut buf).map_err(|e| format!("read embedded binary: {e}"))?;
            return Ok(buf);
        }
    }

    Err(format!("could not find {expected_name} in bun release zip"))
}
